[2024-11-21T12:40:03.259+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-21T12:40:03.280+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.insert_data_to_postgres manual__2024-11-21T12:39:34.953991+00:00 [queued]>
[2024-11-21T12:40:03.291+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.insert_data_to_postgres manual__2024-11-21T12:39:34.953991+00:00 [queued]>
[2024-11-21T12:40:03.293+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-21T12:40:03.311+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): insert_data_to_postgres> on 2024-11-21 12:39:34.953991+00:00
[2024-11-21T12:40:03.321+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4951) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-21T12:40:03.323+0000] {standard_task_runner.py:72} INFO - Started process 4953 to run task
[2024-11-21T12:40:03.324+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'insert_data_to_postgres', 'manual__2024-11-21T12:39:34.953991+00:00', '--job-id', '292', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpp051zzg4']
[2024-11-21T12:40:03.326+0000] {standard_task_runner.py:105} INFO - Job 292: Subtask insert_data_to_postgres
[2024-11-21T12:40:03.393+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.insert_data_to_postgres manual__2024-11-21T12:39:34.953991+00:00 [running]> on host 7a40aa914b11
[2024-11-21T12:40:03.799+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='insert_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T12:39:34.953991+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-21T12:39:34.953991+00:00'
[2024-11-21T12:40:03.802+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-21T12:40:03.803+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-21T12:40:03.805+0000] {logging_mixin.py:190} INFO - Current task name:insert_data_to_postgres state:running start_date:2024-11-21 12:40:03.281200+00:00
[2024-11-21T12:40:03.806+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline and current dag run status:running
[2024-11-21T12:40:03.807+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-21T12:40:03.852+0000] {base.py:84} INFO - Retrieving connection 'skincare_connection'
[2024-11-21T12:40:03.989+0000] {load.py:78} INFO - Successfully inserted records into the database.
[2024-11-21T12:40:03.990+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-21T12:40:04.001+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-21T12:40:04.005+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=insert_data_to_postgres, run_id=manual__2024-11-21T12:39:34.953991+00:00, execution_date=20241121T123934, start_date=20241121T124003, end_date=20241121T124004
[2024-11-21T12:40:04.016+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-21T12:40:04.020+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-21T12:40:04.021+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline queued_at:2024-11-21 12:39:35.005122+00:00
[2024-11-21T12:40:04.022+0000] {logging_mixin.py:190} INFO - Task hostname:7a40aa914b11 operator:PythonOperator
[2024-11-21T12:40:04.064+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-21T12:40:04.080+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-21T12:40:04.083+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
