[2024-11-21T09:56:44.254+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-21T09:56:44.272+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.load_to_postgres manual__2024-11-21T09:52:20.533178+00:00 [queued]>
[2024-11-21T09:56:44.281+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.load_to_postgres manual__2024-11-21T09:52:20.533178+00:00 [queued]>
[2024-11-21T09:56:44.283+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-21T09:56:44.298+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2024-11-21 09:52:20.533178+00:00
[2024-11-21T09:56:44.307+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2441) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-21T09:56:44.309+0000] {standard_task_runner.py:72} INFO - Started process 2443 to run task
[2024-11-21T09:56:44.309+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'load_to_postgres', 'manual__2024-11-21T09:52:20.533178+00:00', '--job-id', '185', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp5jz3npvx']
[2024-11-21T09:56:44.311+0000] {standard_task_runner.py:105} INFO - Job 185: Subtask load_to_postgres
[2024-11-21T09:56:44.359+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.load_to_postgres manual__2024-11-21T09:52:20.533178+00:00 [running]> on host 7a40aa914b11
[2024-11-21T09:56:44.688+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T09:52:20.533178+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-21T09:52:20.533178+00:00'
[2024-11-21T09:56:44.690+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-21T09:56:44.690+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-21T09:56:44.691+0000] {logging_mixin.py:190} INFO - Current task name:load_to_postgres state:running start_date:2024-11-21 09:56:44.273300+00:00
[2024-11-21T09:56:44.692+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline and current dag run status:running
[2024-11-21T09:56:44.693+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-21T09:56:44.721+0000] {base.py:84} INFO - Retrieving connection 'skincare_connection'
[2024-11-21T09:56:44.725+0000] {load.py:54} ERROR - Error inserting data: 'skincare_content'
[2024-11-21T09:56:44.727+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-21T09:56:44.735+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-21T09:56:44.737+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=load_to_postgres, run_id=manual__2024-11-21T09:52:20.533178+00:00, execution_date=20241121T095220, start_date=20241121T095644, end_date=20241121T095644
[2024-11-21T09:56:44.752+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-21T09:56:44.754+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-21T09:56:44.755+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline queued_at:2024-11-21 09:52:20.609108+00:00
[2024-11-21T09:56:44.756+0000] {logging_mixin.py:190} INFO - Task hostname:7a40aa914b11 operator:PythonOperator
[2024-11-21T09:56:44.808+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-21T09:56:44.828+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-21T09:56:44.833+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
