[2024-11-21T10:18:25.658+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-21T10:18:25.687+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.extract_google_trends manual__2024-11-21T10:18:18.274648+00:00 [queued]>
[2024-11-21T10:18:25.703+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.extract_google_trends manual__2024-11-21T10:18:18.274648+00:00 [queued]>
[2024-11-21T10:18:25.707+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-21T10:18:25.737+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_google_trends> on 2024-11-21 10:18:18.274648+00:00
[2024-11-21T10:18:25.752+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2777) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-21T10:18:25.757+0000] {standard_task_runner.py:72} INFO - Started process 2779 to run task
[2024-11-21T10:18:25.756+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'extract_google_trends', 'manual__2024-11-21T10:18:18.274648+00:00', '--job-id', '201', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp2xwtruo8']
[2024-11-21T10:18:25.761+0000] {standard_task_runner.py:105} INFO - Job 201: Subtask extract_google_trends
[2024-11-21T10:18:25.851+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.extract_google_trends manual__2024-11-21T10:18:18.274648+00:00 [running]> on host 7a40aa914b11
[2024-11-21T10:18:26.403+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_google_trends' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T10:18:18.274648+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-21T10:18:18.274648+00:00'
[2024-11-21T10:18:26.405+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-21T10:18:26.406+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-21T10:18:26.408+0000] {logging_mixin.py:190} INFO - Current task name:extract_google_trends state:running start_date:2024-11-21 10:18:25.689014+00:00
[2024-11-21T10:18:26.409+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline and current dag run status:running
[2024-11-21T10:18:26.410+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-21T10:18:26.418+0000] {extract_google_trends.py:131} INFO - Starting Google Trends data scraping...
[2024-11-21T10:18:26.419+0000] {extract_google_trends.py:57} INFO - Running Apify actor for 'sunscreen skin aqua'...
[2024-11-21T10:18:28.200+0000] {extract_google_trends.py:17} INFO - Sent request to Apify API to run actor with status code: 201
[2024-11-21T10:18:29.966+0000] {extract_google_trends.py:31} INFO - Checked actor run status with status code: 200
[2024-11-21T10:18:29.968+0000] {extract_google_trends.py:89} INFO - Actor is still running for 'sunscreen skin aqua'... Waiting...
[2024-11-21T10:18:41.875+0000] {extract_google_trends.py:31} INFO - Checked actor run status with status code: 200
[2024-11-21T10:18:41.877+0000] {extract_google_trends.py:89} INFO - Actor is still running for 'sunscreen skin aqua'... Waiting...
[2024-11-21T10:18:53.097+0000] {extract_google_trends.py:31} INFO - Checked actor run status with status code: 200
[2024-11-21T10:18:53.102+0000] {extract_google_trends.py:89} INFO - Actor is still running for 'sunscreen skin aqua'... Waiting...
[2024-11-21T10:19:04.166+0000] {extract_google_trends.py:31} INFO - Checked actor run status with status code: 200
[2024-11-21T10:19:04.168+0000] {extract_google_trends.py:89} INFO - Actor is still running for 'sunscreen skin aqua'... Waiting...
[2024-11-21T10:19:15.431+0000] {extract_google_trends.py:31} INFO - Checked actor run status with status code: 200
[2024-11-21T10:19:15.433+0000] {extract_google_trends.py:89} INFO - Actor is still running for 'sunscreen skin aqua'... Waiting...
[2024-11-21T10:19:26.500+0000] {extract_google_trends.py:31} INFO - Checked actor run status with status code: 200
[2024-11-21T10:19:26.501+0000] {extract_google_trends.py:89} INFO - Actor is still running for 'sunscreen skin aqua'... Waiting...
[2024-11-21T10:19:37.758+0000] {extract_google_trends.py:31} INFO - Checked actor run status with status code: 200
[2024-11-21T10:19:37.759+0000] {extract_google_trends.py:89} INFO - Actor is still running for 'sunscreen skin aqua'... Waiting...
[2024-11-21T10:19:49.757+0000] {extract_google_trends.py:31} INFO - Checked actor run status with status code: 200
[2024-11-21T10:19:49.758+0000] {extract_google_trends.py:89} INFO - Actor is still running for 'sunscreen skin aqua'... Waiting...
[2024-11-21T10:20:00.890+0000] {extract_google_trends.py:31} INFO - Checked actor run status with status code: 200
[2024-11-21T10:20:00.892+0000] {extract_google_trends.py:89} INFO - Actor is still running for 'sunscreen skin aqua'... Waiting...
[2024-11-21T10:20:11.982+0000] {extract_google_trends.py:31} INFO - Checked actor run status with status code: 200
[2024-11-21T10:20:11.985+0000] {extract_google_trends.py:89} INFO - Actor is still running for 'sunscreen skin aqua'... Waiting...
[2024-11-21T10:20:23.087+0000] {extract_google_trends.py:31} INFO - Checked actor run status with status code: 200
[2024-11-21T10:20:23.089+0000] {extract_google_trends.py:89} INFO - Actor is still running for 'sunscreen skin aqua'... Waiting...
[2024-11-21T10:20:34.298+0000] {extract_google_trends.py:31} INFO - Checked actor run status with status code: 200
[2024-11-21T10:20:34.300+0000] {extract_google_trends.py:87} INFO - Actor run succeeded for 'sunscreen skin aqua'.
[2024-11-21T10:20:35.416+0000] {extract_google_trends.py:45} INFO - Fetched dataset with status code: 200
[2024-11-21T10:20:35.439+0000] {extract_google_trends.py:105} INFO - Data for 'sunscreen skin aqua' saved to 'dags/hasil data extract/GoogleTrend_sunscreen_skin_aqua.json'.
[2024-11-21T10:20:35.451+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl/extract_google_trends.py", line 132, in extract_google_trends
    scrape_and_process_apify(api_token=api_token, actor_id=actor_id, search_terms=search_terms, output_folder=output_folder)
  File "/opt/airflow/dags/etl/extract_google_trends.py", line 119, in scrape_and_process_apify
    writer.writerows(dataset)
  File "/usr/local/lib/python3.12/csv.py", line 167, in writerows
    return self.writer.writerows(map(self._dict_to_list, rowdicts))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/csv.py", line 159, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: 'maxItems', 'maxConcurrency', 'isPublic', 'skipDebugScreen', 'geo', 'isMultiple', 'maxRequestRetries', 'pageLoadTimeoutSecs', 'viewedFrom', 'timeRange', 'searchTerms'
[2024-11-21T10:20:35.473+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-21T10:20:35.474+0000] {logging_mixin.py:190} INFO - Task start:2024-11-21 10:18:25.689014+00:00 end:2024-11-21 10:20:35.472728+00:00 duration:129.783714
[2024-11-21T10:20:35.475+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): extract_google_trends> dag:<DAG: etl_pipeline> dagrun:<DagRun etl_pipeline @ 2024-11-21 10:18:18.274648+00:00: manual__2024-11-21T10:18:18.274648+00:00, state:running, queued_at: 2024-11-21 10:18:18.446742+00:00. externally triggered: True>
[2024-11-21T10:20:35.476+0000] {logging_mixin.py:190} INFO - Failure caused by dict contains fields not in fieldnames: 'maxItems', 'maxConcurrency', 'isPublic', 'skipDebugScreen', 'geo', 'isMultiple', 'maxRequestRetries', 'pageLoadTimeoutSecs', 'viewedFrom', 'timeRange', 'searchTerms'
[2024-11-21T10:20:35.477+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=extract_google_trends, run_id=manual__2024-11-21T10:18:18.274648+00:00, execution_date=20241121T101818, start_date=20241121T101825, end_date=20241121T102035
[2024-11-21T10:20:35.495+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-21T10:20:35.496+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 201 for task extract_google_trends (dict contains fields not in fieldnames: 'maxItems', 'maxConcurrency', 'isPublic', 'skipDebugScreen', 'geo', 'isMultiple', 'maxRequestRetries', 'pageLoadTimeoutSecs', 'viewedFrom', 'timeRange', 'searchTerms'; 2779)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl/extract_google_trends.py", line 132, in extract_google_trends
    scrape_and_process_apify(api_token=api_token, actor_id=actor_id, search_terms=search_terms, output_folder=output_folder)
  File "/opt/airflow/dags/etl/extract_google_trends.py", line 119, in scrape_and_process_apify
    writer.writerows(dataset)
  File "/usr/local/lib/python3.12/csv.py", line 167, in writerows
    return self.writer.writerows(map(self._dict_to_list, rowdicts))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/csv.py", line 159, in _dict_to_list
    raise ValueError("dict contains fields not in fieldnames: "
ValueError: dict contains fields not in fieldnames: 'maxItems', 'maxConcurrency', 'isPublic', 'skipDebugScreen', 'geo', 'isMultiple', 'maxRequestRetries', 'pageLoadTimeoutSecs', 'viewedFrom', 'timeRange', 'searchTerms'
[2024-11-21T10:20:35.539+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-21T10:20:35.563+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-21T10:20:35.570+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
